### PR TITLE
Fix rg useage

### PR DESCRIPTION
**Pull request by XYenon**
It looks like `rg ./ --line-number` will search "./" as regexp. New paramters are from [fzf's doc](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#using-fzf-as-the-secondary-filter).

### CODE REVIEW

**Comment by DreamMaoMao** [comment]
oh i konw what you mean,

It was my mistake but what you did is also a  wrong way. 

It should  set pattern to `.` to match everything.  if  there are no args for rg,  it will match nothing.

image

**Comment by XYenon** [comment]
I have tried this command, and it works well.

```bash
rg --color=always --line-number --no-heading --smart-case "${*:-}" | fzf --ansi --preview='line={2} && begin=$( if [[ $line -lt 7 ]]; then echo $((line-1)); else echo 6; fi ) && bat --highlight-line={2} --color=always --line-range $((line-begin)):$((line+10)) {1}' --delimiter=':' --preview-window up:60% --nth '3..'
```

**Comment by XYenon** [comment]
I think `""` is also a valid pattern to match everything.

**Comment by DreamMaoMao** [comment]
but  "${*:-}"  can't support in fish shell, it better to replace it with `.`

**Comment by XYenon** [comment]
> but "${*:-}" can't support in fish shell, it better to replace it with `.`

Ok, I'll fix it.

**Comment by XYenon** [comment]
I have tested it on zsh, fish, nushell and bash.

**Comment by DreamMaoMao** [comment]
lgtm

**Pull request merged**
